/**
 * \file CanadaBankingHolidayCalendarTest.cpp
 * \brief CanadaBankingHolidayCalendarTest       unit test source file
 *
 */



/*
 * This file is part of OndALear  collection of open source components.
 *
 * This software is provided 'as-is', without any express or implied
 * warranty.  In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Copyright (C) 2008 Amnon Janiv <amnon.janiv@ondalear.com>
 *
 * Initial version: 2011-11-11
 * Author: Amnon Janiv <amnon.janiv@ondalear.com>
 */

/*
 * $Id:  $
 */
#include "CanadaBankingHolidayCalendarTest.hpp"

#include "datetime/Stream.hpp"

#include "xml/XMLHandler.hpp"





namespace ondalear {
namespace test {
namespace calendar {


 
//public member functions
CanadaBankingHolidayCalendarTest::CanadaBankingHolidayCalendarTest()
	:
	HolidayCalendarTest("canada_banking_calendar_test_data.xml")
{
	loadCalendarData(getCalendarDataGrammarFileName(),
		"../../../xml/calendar/canada_banking_holiday_calendar_specs.xml");
}


void
CanadaBankingHolidayCalendarTest::test_2002()
{
	
	CanadaBankingHolidayCalendar cal;
	cal.configure();
	//Family day was not celebrated before 2008; 
	//checking rule behaviour for a rule whose effective date starts after 
	//default rule effective date(i.e. Jan 1 2000)

 
	CPPUNIT_ASSERT(true == cal.isBusinessDay(Date(20020218)));
	CPPUNIT_ASSERT(false == cal.isBusinessDay(Date(20110221)));
}

void
CanadaBankingHolidayCalendarTest::test_2010()
{
	CanadaBankingHolidayCalendar cal;

	//Load the rules
	cal.configure();

	//Compare data generated by the rules to test data loaded from xml test data file
	runCalendaTest(cal, Year(2010));
}

void
CanadaBankingHolidayCalendarTest::test_2011()
{
	 
	CanadaBankingHolidayCalendar cal;

	//Load the rules
	cal.configure();

	//Compare data generated by the rules to test data loaded from xml test data file
	runCalendaTest(cal, Year(2011));


}

void
CanadaBankingHolidayCalendarTest::test_2012()
{
	
	CanadaBankingHolidayCalendar cal;

	//Load the rules
	cal.configure();
	//Compare data generated by the rules to test data loaded from xml test data file
	runCalendaTest(cal, Year(2012));
	 

}

void
CanadaBankingHolidayCalendarTest::test_2002_data_driven()
{
	 BusinessCalendarSharedPtr busCal =
		getBusinessCalendar ("Canada Banking Holiday Calendar");

	CPPUNIT_ASSERT(true == busCal->isBusinessDay(Date(20020218)));
	CPPUNIT_ASSERT(false == busCal->isBusinessDay(Date(20110221)));

	 
}

void 
CanadaBankingHolidayCalendarTest::test_2010_data_driven()
{

	BusinessCalendarSharedPtr busCal =
		getBusinessCalendar ("Canada Banking Holiday Calendar");

	runCalendaTest(*busCal, Year(2010));


}

void
CanadaBankingHolidayCalendarTest::test_2011_data_driven()
{
	BusinessCalendarSharedPtr busCal =
		getBusinessCalendar ("Canada Banking Holiday Calendar");

	runCalendaTest(*busCal, Year(2011));
}

void
CanadaBankingHolidayCalendarTest::test_2012_data_driven()
{
	BusinessCalendarSharedPtr busCal =
		getBusinessCalendar ("Canada Banking Holiday Calendar");

	runCalendaTest(*busCal, Year(2012));
}


} //namespace calendar
} //namespace test
} //namespace ondalear

