/**
 * \file USFederalHolidayCalendarTest.cpp
 * \brief USFederalHolidayCalendar      unit test header file
 *
 */




/*
 * This file is part of OndALear  collection of open source components.
 *
 * This software is provided 'as-is', without any express or implied
 * warranty.  In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Copyright (C) 2008 Amnon Janiv <amnon.janiv@ondalear.com>
 *
 * Initial version: 2011-11-11
 * Author: Amnon Janiv <amnon.janiv@ondalear.com>
 */

/*
 * $Id:  $
 */
#include "USFederalHolidayCalendarTest.hpp"

#include "datetime/Stream.hpp"



namespace ondalear {
namespace test {
namespace calendar {


 
//public member functions
USFederalHolidayCalendarTest::USFederalHolidayCalendarTest()
	:
	HolidayCalendarTest("us_federal_holiday_calendar_test_data.xml")
{
	loadCalendarData(getCalendarDataGrammarFileName(), 
		"../../../xml/calendar/us_federal_holiday_calendar_specs.xml");
}


void
USFederalHolidayCalendarTest::test_2010()
{

	USFederalHolidayCalendar cal;

	//Load the rules
	cal.configure();

	//Compare data generated by the rules to test data loaded from xml test data file
	runCalendaTest(cal, Year(2010));
	
	CPPUNIT_ASSERT(false == cal.isBusinessDay(Date(20101231)));

}

void
USFederalHolidayCalendarTest::test_2011()
{
	
	 
	USFederalHolidayCalendar cal;

	//Load the rules
	cal.configure();

	//Compare data generated by the rules to test data loaded from xml test data file
	runCalendaTest(cal, Year(2011));


}

void
USFederalHolidayCalendarTest::test_2012()
{
	
	USFederalHolidayCalendar cal;

	//Load the rules
	cal.configure();

	//Compare data generated by the rules to test data loaded from xml test data file
	runCalendaTest(cal, Year(2012));

}


void 
USFederalHolidayCalendarTest::test_2010_data_driven()
{

	CalendarSharedPtr calA = getCalendar ("United States Federal Holiday Calendar");
	BusinessCalendarSharedPtr busCalA = 
		CHECKED_SHARED_POINTER_CAST(BusinessCalendar,Calendar,calA);

	runCalendaTest(*busCalA, Year(2010));
}

void
USFederalHolidayCalendarTest::test_2011_data_driven()
{
	CalendarSharedPtr calA = getCalendar ("United States Federal Holiday Calendar");
	BusinessCalendarSharedPtr busCalA = 
		CHECKED_SHARED_POINTER_CAST(BusinessCalendar,Calendar,calA);

	runCalendaTest(*busCalA, Year(2011));
}

void
USFederalHolidayCalendarTest::test_2012_data_driven()
{
	CalendarSharedPtr calA = getCalendar ("United States Federal Holiday Calendar");
	BusinessCalendarSharedPtr busCalA = 
		CHECKED_SHARED_POINTER_CAST(BusinessCalendar,Calendar,calA);

	runCalendaTest(*busCalA, Year(2012));
}

} //namespace calendar
} //namespace test
} //namespace ondalear

